# Generated by Django 6.0.6 on 2026-06-24 08:50

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Detection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_index', models.PositiveIntegerField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('source_ip', models.GenericIPAddressField()),
                ('destination_ip', models.GenericIPAddressField()),
                ('source_port', models.PositiveIntegerField()),
                ('destination_port', models.PositiveIntegerField()),
                ('rf_prediction', models.PositiveSmallIntegerField()),
                ('rf_confidence', models.FloatField()),
                ('reconstruction_error', models.FloatField()),
                ('anomaly_threshold', models.FloatField()),
                ('is_anomaly', models.BooleanField(default=False)),
                ('true_label', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('verdict', models.CharField(choices=[('BENIGN', 'Benign'), ('KNOWN_ATTACK', 'Known Attack'), ('ZERO_DAY', 'Zero-Day Anomaly'), ('CONFIRMED_ATTACK', 'Confirmed Attack')], max_length=20)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], max_length=10)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='EvaluationMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100)),
                ('accuracy', models.FloatField()),
                ('precision', models.FloatField()),
                ('recall', models.FloatField()),
                ('f1_score', models.FloatField()),
                ('false_positive_rate', models.FloatField()),
                ('false_negative_rate', models.FloatField()),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['model_name'],
                'get_latest_by': 'recorded_at',
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('ACKNOWLEDGED', 'Acknowledged'), ('RESOLVED', 'Resolved')], default='ACTIVE', max_length=15)),
                ('handled_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('detection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='alert', to='dashboard.detection')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BlockedIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('blocked_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('active', models.BooleanField(default=True)),
                ('blocked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('source_alert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resulting_blocks', to='dashboard.alert')),
            ],
            options={
                'ordering': ['-blocked_at'],
            },
        ),
        migrations.CreateModel(
            name='UploadBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('DONE', 'Done'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('benign_count', models.PositiveIntegerField(default=0)),
                ('known_attack_count', models.PositiveIntegerField(default=0)),
                ('zero_day_count', models.PositiveIntegerField(default=0)),
                ('confirmed_attack_count', models.PositiveIntegerField(default=0)),
                ('processing_ms', models.FloatField(blank=True, null=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddField(
            model_name='detection',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detections', to='dashboard.uploadbatch'),
        ),
        migrations.AddIndex(
            model_name='detection',
            index=models.Index(fields=['-timestamp'], name='dashboard_d_timesta_98ccdf_idx'),
        ),
        migrations.AddIndex(
            model_name='detection',
            index=models.Index(fields=['verdict'], name='dashboard_d_verdict_e12a4b_idx'),
        ),
        migrations.AddIndex(
            model_name='detection',
            index=models.Index(fields=['severity'], name='dashboard_d_severit_8d1e31_idx'),
        ),
    ]
